

server:
  port: 8181

spring:
  datasource:
  url: jdbc:mysql://localhost:3306/krayondb?serverTimezone=Asia/Seoul
  username: admin
  password: admin11
  driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
# ??? ?? ? ?? DB? ?? ???? ??
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
  ddl-auto: update
  database: mysql # DB ?? ??

logging.level:
  org.hibernate.SQL: debug

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

Jwt:
  secret:
